#
# glBSP Makefile for DJGPP
#

CC=gcc

PROGNAME=glbsp.exe

CFLAGS=-O3 -Wall -DINLINE_G=inline
LIBS=-lm

OBJS=blockmap.o level.o main.o node.o seg.o system.o wad.o


# ----- TARGETS ------------------------------------------------------

all:    $(PROGNAME)

clean:
	rm -f $(PROGNAME) *.o core

$(PROGNAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROGNAME) $(LIBS)

.PHONY: all clean

