all:
	$(MAKE) -C doom
	$(MAKE) -C doom2
	$(MAKE) -C heretic
	$(MAKE) -C hexen
	$(MAKE) -C strife

del:
	$(MAKE) -C doom del
	$(MAKE) -C doom2 del
	$(MAKE) -C heretic del
	$(MAKE) -C hexen del
	$(MAKE) -C strife del

