all:
	$(MAKE) -C doom OUTDIR=../../basev/doom1/progs
	$(MAKE) -C doom2 OUTDIR=../../basev/doom2/progs
	$(MAKE) -C heretic OUTDIR=../../basev/heretic/progs
	$(MAKE) -C hexen OUTDIR=../../basev/hexen/progs
	$(MAKE) -C strife OUTDIR=../../basev/strife/progs

del:
	$(MAKE) -C doom del OUTDIR=../../basev/doom1/progs
	$(MAKE) -C doom2 del OUTDIR=../../basev/doom2/progs
	$(MAKE) -C heretic del OUTDIR=../../basev/heretic/progs
	$(MAKE) -C hexen del OUTDIR=../../basev/hexen/progs
	$(MAKE) -C strife del OUTDIR=../../basev/strife/progs

