EXE=.exe

CFLAGS = -Wall -O3 -ffast-math -fomit-frame-pointer -march=pentiumpro

OBJS = \
	acc.o \
	error.o \
	misc.o \
	parse.o \
	pcode.o \
	strlist.o \
	symbol.o \
	token.o

all: ../bin/acc$(EXE)

../bin/acc$(EXE): $(OBJS)
	gcc -s -o $@ $^ $(LIBS)

%.o : %.c *.h
	gcc $(CFLAGS) -c -o $@ $<
