//**************************************************************************
//**
//**	##   ##    ##    ##   ##   ####     ####   ###     ###
//**	##   ##  ##  ##  ##   ##  ##  ##   ##  ##  ####   ####
//**	 ## ##  ##    ##  ## ##  ##    ## ##    ## ## ## ## ##
//**	 ## ##  ########  ## ##  ##    ## ##    ## ##  ###  ##
//**	  ###   ##    ##   ###    ##  ##   ##  ##  ##       ##
//**	   #    ##    ##    #      ####     ####   ##       ##
//**
//**	Copyright (C) 1999-2000 JÆnis Legzdi·ý
//**
//**	This program is free software; you can redistribute it and/or
//**  modify it under the terms of the GNU General Public License
//**  as published by the Free Software Foundation; either version 2
//**  of the License, or (at your option) any later version.
//**
//**	This program is distributed in the hope that it will be useful,
//**  but WITHOUT ANY WARRANTY; without even the implied warranty of
//**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//**  GNU General Public License for more details.
//**	
//**************************************************************************
//**************************************************************************
//**
//** MobjType.h
//**
//**************************************************************************

char* mobj_names[] =
{
    "misc_PLAYER",
    "misc_zombieman",
    "misc_shotgun_guy",
    "misc_arch_vile",
    "misc_FIRE",
    "misc_REVENANT",
    "misc_TRACER",
    "misc_SMOKE",
    "misc_MANCUBUS",
    "misc_FATSHOT",
    "misc_HEAVY_WEAPON_DUDE",
    "misc_IMP",
    "misc_DEMON",
    "misc_SHADOWS",
    "misc_CACODEMON",
    "misc_BARON_OF_HELL",
    "misc_BRUISERSHOT",
    "misc_HELL_KNIGHT",
    "misc_LOST_SOUL",
    "misc_THE_SPIDER_MASTERMIND",
    "misc_ARACHNOTRON",
    "misc_THE_CYBERDEMON",
    "misc_PAIN_ELEMENTAL",
    "misc_WOLFSS",
    "misc_KEEN",
    "misc_BOSSBRAIN",
    "misc_BOSSSPIT",
    "misc_BOSSTARGET",
    "misc_SPAWNSHOT",
    "misc_SPAWNFIRE",
    "misc_BARREL",
    "misc_TROOPSHOT",
    "misc_HEADSHOT",
    "misc_ROCKET",
    "misc_PLASMA",
    "misc_BFG",
    "misc_ARACHPLAZ",
    "misc_PUFF",
    "misc_BLOOD",
    "misc_TFOG",
    "misc_IFOG",
    "misc_TELEPORTMAN",
    "misc_EXTRABFG",
    "misc_MISC0",
    "misc_MISC1",
    "misc_MISC2",
    "misc_MISC3",
    "misc_MISC4",
    "misc_MISC5",
    "misc_MISC6",
    "misc_MISC7",
    "misc_MISC8",
    "misc_MISC9",
    "misc_MISC10",
    "misc_MISC11",
    "misc_MISC12",
    "misc_INV",
    "misc_MISC13",
    "misc_INS",
    "misc_MISC14",
    "misc_MISC15",
    "misc_MISC16",
    "misc_MEGA",
    "misc_CLIP",
    "misc_MISC17",
    "misc_MISC18",
    "misc_MISC19",
    "misc_MISC20",
    "misc_MISC21",
    "misc_MISC22",
    "misc_MISC23",
    "misc_MISC24",
    "misc_MISC25",
    "misc_CHAINGUN",
    "misc_MISC26",
    "misc_MISC27",
    "misc_MISC28",
    "misc_SHOTGUN",
    "misc_SUPERSHOTGUN",
    "misc_MISC29",
    "misc_MISC30",
    "misc_MISC31",
    "misc_MISC32",
    "misc_MISC33",
    "misc_MISC34",
    "misc_MISC35",
    "misc_MISC36",
    "misc_MISC37",
    "misc_MISC38",
    "misc_MISC39",
    "misc_MISC40",
    "misc_MISC41",
    "misc_MISC42",
    "misc_MISC43",
    "misc_MISC44",
    "misc_MISC45",
    "misc_MISC46",
    "misc_MISC47",
    "misc_MISC48",
    "misc_MISC49",
    "misc_MISC50",
    "misc_MISC51",
    "misc_MISC52",
    "misc_MISC53",
    "misc_MISC54",
    "misc_MISC55",
    "misc_MISC56",
    "misc_MISC57",
    "misc_MISC58",
    "misc_MISC59",
    "misc_MISC60",
    "misc_MISC61",
    "misc_MISC62",
    "misc_MISC63",
    "misc_MISC64",
    "misc_MISC65",
    "misc_MISC66",
    "misc_MISC67",
    "misc_MISC68",
    "misc_MISC69",
    "misc_MISC70",
    "misc_MISC71",
    "misc_MISC72",
    "misc_MISC73",
    "misc_MISC74",
    "misc_MISC75",
    "misc_MISC76",
    "misc_MISC77",
    "misc_MISC78",
    "misc_MISC79",
    "misc_MISC80",
    "misc_MISC81",
    "misc_MISC82",
    "misc_MISC83",
    "misc_MISC84",
    "misc_MISC85",
    "misc_MISC86",
	0
};
