#
# Timidity Makefile for Borland C++
#
!if !$d(BCB)
BCB = $(MAKEDIR)\..
!endif

OBJS=common.obj controls.obj filter.obj instrum.obj \
    mix.obj output.obj playmidi.obj readmidi.obj \
    resample.obj tables.obj timidity.obj

.cpp.obj:
    bcc32 -c -O2 -q {$< }

timidity.lib: $(OBJS)
    tlib $@ /a $(OBJS)
